### ISSUE TITLE
Add readme.md

### ISSUE THREAD

**Issue by zonky2** [pipisso/pip-elements#1]
pls!

**Comment by pipisso** [comment]
I have created this package for internal use only.
So I think that nobody will ever use it.
It includes only three things:

- Mega Menu (Basically the same as [this](https://github.com/DERHAEUPTLING/contao-mega-menu) with some rewrites for Contao >=5)
- ContentBox (A ContentElement for Wrapping Content with some Options)
![Bildschirmfoto 2023-09-27 um 22 31 21](https://github.com/pipisso/pip-elements/assets/90516172/1d600ccf-671c-43a3-9db7-348302b66e91)
- ProductBox 
![Bildschirmfoto 2023-09-27 um 22 30 23](https://github.com/pipisso/pip-elements/assets/90516172/2df0647d-7ba8-4a62-a7cf-70f3cea2af64)
![Bildschirmfoto 2023-09-27 um 22 30 59](https://github.com/pipisso/pip-elements/assets/90516172/9f5b6558-ff4a-4a22-a28a-1f1fa6aa6c85)
